<?php
$this->layout('system::layout/default', [
    'title' => $page_title,
    'page_title' => $page_title,
]);
?>

<div class="row">
    <div class="col-md-6">
        <div class="alert alert-danger">
            <div class="pb-2">
                Really want to delete <?= $caption_html ?>?
            </div>
            <div>
                <a href="<?= $data['delete_url'] ?>" class="btn btn-danger btn-sm"><?= d__('system', 'Delete') ?></a>
                <a href="<?= $data['back_url'] ?>" class="btn btn-primary btn-sm"><?= d__('system', 'Cancel') ?></a>
            </div>
        </div>
    </div>
</div>
