<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Akbarali">
    <title id="time_title"><?=$data['ads']->time_ads?></title>
    <script type="text/javascript" src="<?=$config['homeurl']?>/ads_akb/jquery.js"></script>
    <link rel="stylesheet" href="<?=$config['homeurl']?>/ads_akb/surfing.css" type="text/css">
  </head>
  <body id="click">
   <script>
      function viewing_surfing(code){
      	var code = $.trim(code);
      var Csrf = '<?= $csrf_token ?>';
      	$.ajax({
      		type: 'POST', 
      		url: '<?=$config['homeurl']?>/api_akbarali/adscheck/',   
      		data: { 'Csrf' : Csrf, 'ads_id' : <?=$data['ads']->id;?> }, 
      		success: function(a) {
      		 var data = JSON.parse(a);
      		 if(data.success){
      		 // alert(data.success.link);
      		  window.location.href = data.success.link;
      		 }
      		 }
      	});
      }
      
      var w = window, d=document, active = 1, lactive=1;
      var isa = 1;
      $(w).focus(function(){active=1}).blur(function(){active=0});
      
      function timer(){
      	lactive=((typeof d.hasFocus != 'undefined' ? d.hasFocus() : active) ? 1 : 0);
      	
      	var obj   = document.getElementById('time');
      	var obj_t = document.getElementById('time_title');
      
      	if(isa&&lactive||!isa){
      		obj.innerHTML--;
      		obj_t.innerHTML--;
      		$('#echo_all').html('');
			
      	} else if(isa&&!lactive){
      		$('#echo_all').html('<span style="color:#e32636;">Окно неактивно</span>');
			$('#time_title').html('Окно неактивно');
      	}
      
      	if(obj.innerHTML == 0){
      		var Csrf = '<?= $csrf_token ?>';
      		//$('#echo_all').html('<span style="color:blue;">Reklamani ko`rib bo`ldim</span> <button>Button</button>');
			$.ajax({
      			type: 'POST', 
				     url: '<?=$config['homeurl']?>/api_akbarali/adsview/',  
      			data: { 'Csrf' : Csrf, 'ads_id' : <?=$data['ads']->id;?> }, 
      			beforeSend: function(){ $('#timer_lo').remove(); $('#code').css({display: 'block'}); },
      			success: function(data){ $('#code').html(data); }
      		});
      		setTimeout(function(){},1000);
      
      	}else{ setTimeout(timer,1000); }
      
      }
      setTimeout(timer,1000);	
      
    </script>
    <table class="table_gl" style="position: absolute; bottom: 0px;">
      <tbody>
        <tr>
          <td style="width: 30%; padding-left: 20px; " rowspan="2"><span class="echo_sr" id="echo_all"></span></td>
          <td style="width: 30%; padding-left: 10px;" rowspan="2">
            <div id="timer_lo">
              <div class="timer notranslate"><span id="time"><?=$data['ads']->time_ads?></span></div>
            </div>
            <div id="code" style="display: none;"></div>
            <div id="timer_lo_error"></div>
          </td>
          <td style="width: 40%;" rowspan="2">
            <center>
              <a href="https://socpublic.com/?i=3397782&slide=1" target="_blank" title="Socpublic">
                <div style="background: url(http://socpublic.com/storage/banners/banner_7_468x60.gif); width: 468px; height: 60px; margin-top: 20px; margin-bottom: 20px;"></div>
              </a>
            </center>
          </td>
        </tr>
      </tbody>
    </table>
    
    <iframe style="padding-bottom: 80px;" src="<?=$data['ads']->link;?>" id="framesite" scrolling="yes" frameborder="0" height="100%" width="100%"></iframe>
   
    <!--<a onClick="viewing_surfing('2fa51cf77fe057312870c05c00d36147', 'surf');" class='button_s'>Пройти проверку</a>-->
     </body>
</html>