<?php

/**
 * @var $title
 * @var $page_title
 * @var $current_section
 * @var $user
 * @var $articles Illuminate\Contracts\Pagination\LengthAwarePaginator
 * @var $sections \Blog\Models\BlogSection
 */

$this->layout('system::layout/default');
?>
<?php if ($user->rights >= 9): ?>
    <div class="mb-3 mt-n1">
        <a href="/blog/admin/" class="btn btn-outline-danger btn-sm"><?= __('Admin panel') ?></a>
    </div>
<?php endif ?>
<div class="row">
    <div class="col-12 col-xl-9">
        <?php if ($articles->count() > 0): ?>
            <?php foreach ($articles as $article): ?>
                <?php /** @var $article \Blog\Models\BlogArticle */ ?>
                <div class="card border-0 mb-2 shadow">
                    <div class="card-body">
                        <h3 class="card-title mb-0"><a href="<?= $article->url ?>"><?= $article->name ?></a></h3>
                        <?php if ($article->preview_text_safe): ?>
                            <p class="card-text mt-2"><?= $article->preview_text_safe ?></p>
                        <?php endif ?>
                        <div class="d-flex pt-2">
                            <div class="text-muted forum-view-counter">
                                <svg class="icon download-button-icon mt-n1 mr-1">
                                    <use xlink:href="<?= $this->asset('blog/icons/icons.svg') ?>#rating"/>
                                </svg>
                                <?php if ($article->rating > 0): ?>
                                    <span class="text-success font-weight-bold"><?= $article->rating ?></span>
                                <?php elseif ($article->rating < 0): ?>
                                    <span class="text-danger font-weight-bold"><?= $article->rating ?></span>
                                <?php else: ?>
                                    <span class="font-weight-bold"><?= $article->rating ?></span>
                                <?php endif; ?>
                            </div>
                            <div class="text-muted forum-view-counter ml-3">
                                <svg class="icon download-button-icon mt-n1 mr-1">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#eye"/>
                                </svg>
                                <?= (int) $article->view_count ?>
                            </div>
                            <div class="text-muted forum-view-counter ml-3">
                                <svg class="icon download-button-icon mr-1">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                                </svg>
                                <?= $article->comments_count ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="mt-3">
                <?= $articles->render() ?>
            </div>
        <?php else: ?>
            <div class="alert alert-info"><?= __('The list is empty') ?></div>
        <?php endif; ?>
    </div>
    <div class="col-12 col-xl-3">
        <form action="/blog/" method="get" class="mb-3 pl-0 pl-xl-3">
            <input type="hidden" name="action" value="search">
            <div class="input-group">
                <input type="text" name="query" id="query" class="form-control" placeholder="<?= __('Search query') ?>">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit"><?= __('Search') ?></button>
                </div>
            </div>
        </form>
        <?php if ($sections->count() > 0): ?>
            <h3 class="pl-0 pl-xl-3"><?= __('Categories') ?></h3>
            <nav class="nav flex-column">
                <?php foreach ($sections as $section): ?>
                    <?php /** @var $section \Blog\Models\BlogSection */ ?>
                    <a class="nav-link pl-0 pl-xl-3" href="<?= $section->url ?>"><?= $section->name ?></a>
                <?php endforeach; ?>
            </nav>
        <?php endif; ?>
    </div>
</div>

<?php $this->push('styles') ?>
<link rel="stylesheet" href="<?= $this->asset('blog/css/blog.css', true) ?>">
<?php $this->stop(); ?>
<?php $this->push('scripts') ?>
<script async charset="utf-8" src="//cdn.embedly.com/widgets/platform.js"></script>
<script>
    document.querySelectorAll('oembed[url]').forEach(element => {
        const anchor = document.createElement('a');
        anchor.setAttribute('href', element.getAttribute('url'));
        anchor.className = 'embedly-card';
        element.appendChild(anchor);
    });
</script>
<?php $this->stop(); ?>
