<?php
/*
 * Akbarali yozgan 
 * Sana: 30.10.2020
 * Bog`lanish: Akbarali@uzhackersw.uz
 * Sayt: UzHackerSW.uz
 * Modifikatsiya: 03/11/2020
 * Johncms Профил: https://johncms.com/profile/?user=38217
 * На тему: https://johncms.com/forum/?type=topic&id=12200
 */
  $this->layout(
      'system::layout/default',[
          'title'      => $data['title'], // Передаем заголовок страницы в тег title
          'page_title' => $data['page_title'], // Передаем заголовок страницы в тег h1
      ]
  );
  $user = di(Johncms\Users\User::class);
  ?>
<div>Загрузить фотографии:</div>
<!-- File upload form -->
<form id="uploadForm" enctype="multipart/form-data">
  <div class="form-group">
    <div class="custom-file">
      <input type="file" name="input_file_name" id="fileInput" class="custom-file-input">
      <label for="file" class="custom-file-label">Выберите файл</label>
    </div>
    <hr>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" style="width: 0%;  animation: progress-bar-stripes 2s linear infinite;">
      </div>
    </div>
    <div id="uploadStatus"></div>
    <hr>
    <div class="text-muted mb-3 small">
      Разрешенные форматы изображений: JPG, GIF или PNG. Размер файла не должен превышать 1000 Кб.<br>The новое изображение заменит старое (если было).        
    </div>
  </div>
  <div class="mt-3">
    <input type="submit" name="submit" value="Сохранить" class="btn btn-primary">
  </div>
</form>
<hr>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3" id="boshi">
  <?php foreach ($data['rasm'] as $photo): ?>
  <div class="col mb-4">
    <div class="card py-0 h-100 overflow-hidden">
      <div class="album-photo" style="background: url('/upload/images_akb/<?=$photo['id']?>.png');"></div>
      <div class="card-body d-flex px-3 flex-column justify-content-between" style=" padding: 10px; ">
        <div class="small">
          <span class="text-nowrap pr-2">
          Добавлено: <a href="../profile/?user=<?=$photo['uploader_id']?>"><?=$photo['name']?></a><br>
          </span> 
           <?php // if ($user->rights >= 7): ?>
          <span class="text-nowrap">
          Действия: <a href="#" id="dellete" data-value="<?=$photo['id']?>">удалять</a>
          </span>
          <?php //endif; ?>
        </div>
      </div>
      <div class="card-footer d-flex justify-content-between" style=" padding-bottom: 0px; ">
        <div class="input-group mb-3">
          <input type="text" value="[img]<?=$photo['id']?>.png[/img]" id="photo<?=$photo['id']?>" class="form-control">
          <button onclick="copybbcode('photo<?=$photo['id']?>')" class="btn btn-primary" class="btn btn-outline-secondary">Copy</button>
        </div>
      </div>
    </div>
  </div>
  <?php endforeach; ?>
</div>
<hr>
<?= $data['pagination'] ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Progress bar -->
<script>
$(document).on("click", "#dellete", function() {
    var a = $(this).data("value"),
     b = confirm("Do you want to permanently delete this image?");
    if (true == b)
    $.ajax({
        url: "dellete.php",
        type: "POST",
        data: {id: a},
        success: function(text) {
         var resp = JSON.parse(text);
            if(resp.success){
            alert(resp.success.id); 
            }else if(resp.error){
            alert(resp.error.cause); 
            }
            
        }
    });
});

  function copybbcode(bbcode){
      var copyText = document.getElementById(bbcode);
    copyText.select();
    copyText.setSelectionRange(0, 99999)
    document.execCommand("copy");
      }
    $(document).ready(function(){
        // File upload via Ajax
        $("#uploadForm").on('submit', function(e){
            e.preventDefault();
            $.ajax({
                xhr: function() {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener("progress", function(evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = ((evt.loaded / evt.total) * 100);
                            $(".progress-bar").width(percentComplete + '%');
                            $(".progress-akb").val(percentComplete);
                            $(".progress-bar").html(percentComplete+'%');
                        }
                    }, false);
                    return xhr;
                },
                type: 'POST',
                url: 'upload.php',
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData:false,
                beforeSend: function(){
                    $(".progress-bar").width('0%');
                     $(".progress-akb").val('0');
                    $('#uploadStatus').html('<p style="color:#28A74B;">Файл загружается!</p>');
                },
                error:function(){
                    $('#uploadStatus').html('<p style="color:#EA4335;">File upload failed, please try again.</p>');
                },
                success: function(text){
                    var resp = JSON.parse(text);
                    if(resp.success){
                        $('#uploadForm')[0].reset();
                        $('#uploadStatus').html('<p style="color:#28A74B;">Файл успешно загружен!</p>');
         $('#boshi').prepend('<div class="col mb-4"><div class="card py-0 h-100 overflow-hidden"><div class="album-photo" style="background: url(&quot;/upload/images_akb/'+resp.success.id+'.png&quot;);"></div> <div class="card-footer d-flex justify-content-between"><div class="small"><span class="text-nowrap"><input type="text" value="'+resp.success.name+'" id="photo'+resp.success.id+'"> <button onclick="copybbcode(\'photo'+resp.success.id+'\')" class="btn btn-primary">Copy</button></span></div></div></div></div>');
                    }else if(resp.error){
                        $('#uploadStatus').html('<p style="color:#EA4335;">Please select a valid file to upload.</p>');
                    alert(resp.error.cause);
                    }
                    else{
                        alert(resp.error.cause);
                    }
                }
            });
        });
        
        // File type validation
        $("#fileInput").change(function(){
            var allowedTypes = ['image/jpeg', 'image/png', 'image/jpg', 'image/gif'];
            var file = this.files[0];
            var fileType = file.type;
            if(!allowedTypes.includes(fileType)){
                alert('Ошибка формата файла Разрешается: (JPEG/JPG/PNG/GIF).');
                $("#fileInput").val('');
                return false;
            }
        });
    });
</script>